import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from tools.aris_geo.compiler import replace_compiled_block


REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures" / "profound"
VERIFY_SCRIPT = REPO_ROOT / "tools" / "verify_evidence.py"
SCORE_SCRIPT = REPO_ROOT / "tools" / "score.py"
COMPILE_SCRIPT = REPO_ROOT / "tools" / "compile_readme.py"


class OfflineVerticalSliceTests(unittest.TestCase):
    def setUp(self):
        self.tempdir = Path(tempfile.mkdtemp(prefix="aris-geo-vertical-slice-"))
        self.addCleanup(lambda: shutil.rmtree(self.tempdir))
        self.repo_root = self.tempdir / "repo"
        (self.repo_root / ".git").mkdir(parents=True)

    def test_profound_fixture_reproduces_committed_profile_and_readme(self):
        # Break caught: the repository claims an offline Profound slice, but the fixture/docs state
        # cannot be regenerated by the production CLIs.
        fixture_profile = FIXTURE_ROOT / "wiki" / "products" / "profound.json"
        fixture_raw_dir = FIXTURE_ROOT / "wiki" / "raw" / "profound"
        committed_profile = REPO_ROOT / "wiki" / "products" / "profound.json"
        committed_raw_dir = REPO_ROOT / "wiki" / "raw" / "profound"
        committed_readme = REPO_ROOT / "README.md"

        for required in (
            fixture_profile,
            fixture_raw_dir,
            committed_profile,
            committed_raw_dir,
            committed_readme,
            REPO_ROOT / "docs" / "METHODOLOGY.md",
            REPO_ROOT / "LICENSE",
            REPO_ROOT / ".github" / "workflows" / "verify.yml",
            REPO_ROOT / ".github" / "workflows" / "freshness.yml",
        ):
            self.assertTrue(required.exists(), f"missing repository artifact: {required}")

        shutil.copytree(FIXTURE_ROOT / "wiki", self.repo_root / "wiki")
        self._assert_matching_tree(fixture_raw_dir, committed_raw_dir)

        profile = json.loads((self.repo_root / "wiki" / "products" / "profound.json").read_text(encoding="utf-8"))
        profile["scores"] = {}
        profile["risk_flags"] = []
        for claim in profile.get("effect_claims") or []:
            if isinstance(claim, dict):
                claim.pop("grade_final", None)
        self._write_json(self.repo_root / "wiki" / "products" / "profound.json", profile)

        committed_readme_text = committed_readme.read_text(encoding="utf-8")
        blank_readme = replace_compiled_block(committed_readme_text, "")
        (self.repo_root / "README.md").write_text(blank_readme, encoding="utf-8")

        score_result = self._run(SCORE_SCRIPT)
        self.assertEqual(0, score_result.returncode, score_result.stderr)
        regenerated_profile_text = (self.repo_root / "wiki" / "products" / "profound.json").read_text(encoding="utf-8")
        self.assertEqual(
            committed_profile.read_text(encoding="utf-8"),
            regenerated_profile_text,
        )
        regenerated_profile = json.loads(regenerated_profile_text)
        flags = [flag["flag"] for flag in regenerated_profile.get("risk_flags", []) if isinstance(flag, dict)]
        self.assertIn("入门档仅覆盖单一引擎", flags)
        self.assertNotIn("入门档仅覆盖单一引擎 / 仅 1 个席位", flags)

        verify_result = self._run(VERIFY_SCRIPT, "--strict")
        self.assertEqual(0, verify_result.returncode, verify_result.stderr)

        compile_result = self._run(COMPILE_SCRIPT)
        self.assertEqual(0, compile_result.returncode, compile_result.stderr)
        self.assertEqual(
            committed_readme_text,
            (self.repo_root / "README.md").read_text(encoding="utf-8"),
        )
        regenerated_readme = (self.repo_root / "README.md").read_text(encoding="utf-8")
        self.assertIn("- 🟡 入门档仅覆盖单一引擎", regenerated_readme)
        self.assertNotIn("仅 1 个席位", regenerated_readme)

        score_check = self._run(SCORE_SCRIPT, "--check")
        self.assertEqual(0, score_check.returncode, score_check.stderr)

        compile_check = self._run(COMPILE_SCRIPT, "--check")
        self.assertEqual(0, compile_check.returncode, compile_check.stderr)

    def test_repository_docs_disclose_synthetic_fixture_and_live_requirements(self):
        # Break caught: repository documentation implies live findings or omits the exact offline/live contracts.
        readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
        methodology = (REPO_ROOT / "docs" / "METHODOLOGY.md").read_text(encoding="utf-8")

        for snippet in (
            "synthetic offline fixture",
            "Python 3.11+",
            "ARIS-Code v0.4.21+",
            "python3 -m unittest discover -s tests -v",
            "python3 tools/verify_evidence.py --strict",
            "python3 tools/score.py --check",
            "python3 tools/compile_readme.py --check",
            "TAVILY_API_KEY",
            "EXECUTOR_API_KEY",
            "OPENAI_API_KEY",
            "ARIS_DISABLE_KEYCHAIN=1",
            "python3 tools/geo_loop.py --limit 1",
            "live smoke is not run here",
            "Do not commit API keys",
        ):
            self.assertIn(snippet, readme)

        for snippet in (
            "synthetic offline fixture",
            "维度集由海外标杆归纳,国内适配性未验证",
            "`market: domestic | overseas` 的差异化必填字段集在 v1 只做了粗分",
            "「未披露」≠「没有」",
            "发现机制存在自指偏差",
            "三个 persona 同模型,共享先验",
            "无综合总分排名",
            "标签必须能消失",
        ):
            self.assertIn(snippet, methodology)

    def _assert_matching_tree(self, expected_dir: Path, actual_dir: Path) -> None:
        expected_files = sorted(
            path.relative_to(expected_dir)
            for path in expected_dir.rglob("*")
            if path.is_file()
        )
        actual_files = sorted(
            path.relative_to(actual_dir)
            for path in actual_dir.rglob("*")
            if path.is_file()
        )
        self.assertEqual(expected_files, actual_files)
        for relative_path in expected_files:
            self.assertEqual(
                (expected_dir / relative_path).read_text(encoding="utf-8"),
                (actual_dir / relative_path).read_text(encoding="utf-8"),
            )

    def _write_json(self, path: Path, payload: dict) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    def _run(self, script: Path, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(script), *args],
            cwd=self.repo_root,
            text=True,
            capture_output=True,
            check=False,
        )


if __name__ == "__main__":
    unittest.main()
